# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Ruff - Python linter and formatter (extremely fast)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      # Run the linter
      - id: ruff-check
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  # Mypy - Static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        additional_dependencies: [
          mypy,
          types-requests,
          types-PyYAML,
          torch,
          transformers
        ]
        args: [--ignore-missing-imports, --no-strict-optional]

  # nbqa - Quality assurance for Jupyter notebooks
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      # Apply ruff linting to notebooks (with ignore for notebook-specific issues)
      - id: nbqa-ruff
        args: ["--fix", "--ignore=E402,F401,E703"]
      # Apply mypy type checking to notebooks (relaxed for notebooks)
      - id: nbqa-mypy
        additional_dependencies: [
          mypy,
          types-requests,
          types-PyYAML,
          torch,
          transformers
        ]
        args: [--ignore-missing-imports, --no-strict-optional]

  # Additional useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Check for merge conflicts
      - id: check-merge-conflict
      # Check YAML syntax
      - id: check-yaml
      # Check TOML syntax
      - id: check-toml
      # Remove trailing whitespace
      - id: trailing-whitespace
      # Ensure files end with newline
      - id: end-of-file-fixer
      # Check for large files
      - id: check-added-large-files
        args: ['--maxkb=1000']

  # Jupyter notebook specific hooks
  - repo: https://github.com/srstevenson/nb-clean
    rev: 3.3.0
    hooks:
      # Clean notebook outputs and metadata
      - id: nb-clean
        args: [--remove-empty-cells, --preserve-cell-outputs]
